name: Deployment

on:
  push:
    branches:
      - master

jobs:

  push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_TAG }}


  deploy-to-render:
    runs-on: ubuntu-latest
    needs: push-to-docker-hub
    steps:
      - name: Trigger Redeployment
        run: |
          curl -X POST ${{ secrets.REDEPLOY_HOOK }}